apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: bg
  namespace: next
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: gcr.io/knative-samples/knative-route-demo:blue
            env:
            - name: T_VERSION
            value: "blue"