apiVersion: serving.knative.dev/v1alpha1
kind: Configuration
metadata:
  name: bg # Configuration name is unchanged, since we're updating an existing Configuration
  namespace: next
spec:
  revisionTemplate:
    metadata:
      labels:
        knative.dev/type: container
    spec:
      container:
        image: gcr.io/knative-samples/knative-route-demo:green # URL to the new version of the sample app docker image
        env:
          - name: T_VERSION
            value: "green" # Updated value for the T_VERSION environment variable