apiVersion: serving.knative.dev/v1alpha1
kind: Configuration
metadata:
  name: blue-green # Configuration name is unchanged, since we're updating an existing Configuration
  namespace: default
spec:
  revisionTemplate:
    metadata:
      labels:
        knative.dev/type: container
    spec:
      container:
        image: gcr.io/knative-samples/knative-route-demo:green # URL to the new version of the sample app docker image
        imagePullPolicy: Always
        env:
          - name: T_VERSION
            value: "green" # Updated value for the T_VERSION environment variable
---
apiVersion: serving.knative.dev/v1alpha1
kind: Route
metadata:
  name: blue-green # Route name is unchanged, since we're updating an existing Route
  namespace: default
spec:
  traffic:
  - revisionName: blue-green-00001
    percent: 100 # All traffic still going to the first revision
  - revisionName: blue-green-00002
    percent: 0 # 0% of traffic routed to the second revision
    name: v2 # A named route