apiVersion: v1
kind: Secret
metadata:
  name: builder-secret
  annotations:
    build.knative.dev/docker-0: https://gcr.io
type: kubernetes.io/basic-auth
stringData:
  username: _json_key
  password: |
    {
      "type": "service_account",
      "project_id": "s9-demo",
      "private_key_id": "8fe8cf7e7481511f84be4fb66f74813e2365e6c5",
      "private_key": "...",
      "client_email": "...",
      "client_id": "...",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/kbuilder%40s9-demo.iam.gserviceaccount.com"
    }
