apiVersion: v1
kind: Secret
metadata:
  name: builder-secret
  annotations:
    build.knative.dev/docker-0: https://gcr.io
type: kubernetes.io/basic-auth
stringData:
  username: _json_key
  password: |
    {
      "type": "service_account",
      "project_id": "s9-demo",
      "private_key_id": "8fe8cf7e7481511f84be4fb66f74813e2365e6c5",
      "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDaEk67l85mooYT\nTucn70rlcdkBdZA1iiBP5Gn/uLjmAsqpC3MmtADSeYxmDETwAKeuBLa2XU0Xg9Lg\nnz+xItbW8yLb5fgbQFrqcKR0Y9tEGMsdOyiz0cBGGDZI0DHBJBC609FFRA4EMzL6\n6pdm7SqGTw2E+sNU5NKT0/+6CzxAG103i4gWSfSm7nMU2qnNucpMorqSCK/3i/vg\n59iKg2G6O2V40Ob1l+VNLc8N3y6H7nmewfjIyRrHpeeN0hcR7buT51x6D7RW2yVK\n2BU/WXrp4+6flk33jsiIq6366/UYhcG2nuDpBY9ksVhwLXuBvTUyb1TwBek6m9q1\nceGGrIbxAgMBAAECggEAR+hyitxPhLuB35sMkTgQZ+FnL9p+35C4/+8vXtIgMkRo\nZF6wrWn8vWq0N7BDCSsGH9VRFIhmk+L1pfkNLRFya3XIIF/QNNg/QoA7Ul/dHTLZ\nwz1POiBnuRVhzRfN2ETWuWyAXMlIn+zsGh5CJ3/8HkayDBAOWg+MOo/VCxmKWA6y\nCDCIX5U9t5txIZ4e/cvu2bN+6KUD1vXQ99EtwI2HsRDqcKt3lFLhs5lc17ikmOa9\nOiDIN+sCBlGnRjNQ1ISPgPA5Hk/CE/Y4elzJ5fLqZ5Bls8elSc9+4Sq8zn0thzwT\nd/G9KiSVCvRCJVoQjxsBiH3ZAFxt+F+Ju9l3nz3yWwKBgQDyxeSsFJ4Va1/M4afY\niGJmlgKqqq6+2itkHVHG9UWk9TbbQzcgVIYZCt3adFDbhpxsJTbyCZ0SoLbCX5Nx\nApqzjnIZ318s3JybuBLK0YAQ3BP/Hef8KF4IS5xfoJog/05Dlp8ed2Z4JmcMwCKv\nGyKzkEalUByCgdL5W3yX4TmgrwKBgQDl8+MRASwn3OMlAv/rX+zF3ldR5AYDMTMs\n/lveNathxc9l8o2KttBAzprXW1Qe4Dr7GN3zaVy1R2PtyLwHARw+LoIMH6hSOIZI\nsnxEsVm7ntckCTU9ZidXxxnWahM7ydQ1Sf82nSuyH+hHpxuUWVdQTmuZSU/J/pHm\nuxmDbFH6XwKBgFJqK77fIOtUkCkVUc2IPx9kPXOCjd/sYF6UNXa9PO9K71xv7P7k\nssE9lyLZ6bkccW2lFIoGCXSRanmByKPMpofeC44M7lpkaiXSz05a4IbYr1Ej7eUE\nLyfRwzwTYT9ibEc1kr7c+cRABSum7h9TruwWRmVIVOVY/S35iMpmgxGxAoGBAOEY\nuWiW5jtrTWqYoh4tO2CCAqYl+QC886SSpSlDDi3abegU5BsqU3dtB0PSoejLhNDx\niarRs6+8X4SPoAeXPadc7W6iuqkprcGR/nVbykQP+/fJj7U3v0F8o70w/vzi1/kG\nI265seFevIkPer7gKclxyoA1tIY9zWK4OgRdT24vAoGAK+uVu4xJi7u8YL4cyOdr\nF7iir61IwLQCcPLFbY93E+dPIW9JJFY9gtHhENWcL8hoSyvbBUB7RfH3RMVKY3jz\n6pWAEQxPngVgGvBriHxnvfbUC2yluQrNmueYLb0ewr8uDTOatxJkR83/2G+TITbr\n7zbf7bf0YTjMaHO88X1DpVM=\n-----END PRIVATE KEY-----\n",
      "client_email": "kbuilder@s9-demo.iam.gserviceaccount.com",
      "client_id": "106040380447226089846",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/kbuilder%40s9-demo.iam.gserviceaccount.com"
    }
